### ISSUE TITLE
Some questions regarding the code structure

### ISSUE THREAD

**Issue by josdejong** [infusion/Complex.js#1] opened 2016-02-04 19:40 UTC
Hi Robert, great work with this library, it looks well taken care of.

I was looking through the code and wondering why you use the following structure (you have something similar in Fraction):
```js
        /**
         * Adds two complex numbers
         *
         * @returns {Complex}
         */
        "add": function(a, b) {

            parse(a, b);
            
            return new Complex(
                this["re"] + P["re"],
                this["im"] + P["im"]);
        },
        
```

The function `parse` parses the input for the second argument of the function `add`, but `parse` moves the result in some global variable `P`, which is then used to do the operation on. Such structures using globals are very fragile. Can't you change `parse` into a pure function without side effects, something like this: 
```js
        /**
         * Adds two complex numbers
         *
         * @returns {Complex}
         */
        "add": function(a, b) {

            var other = parse(a, b);
            
            return new Complex(
                this["re"] + other["re"],
                this["im"] + other["im"]);
        },
```
No magic, and no risk of `P` being changed accidentally between parsing it and using it.

**Comment by infusion** [comment] 2016-02-04 19:53
I know these things can lead to very strange behavior, but as JavaScript is a single-threaded language, there is no danger of crosstalk. I implemented this quite carefully and decided to use the global parse object `P` in order to avoid thrashing the garbage collector whenever a new object must be created and thrown away. It might be that future versions of v8 or spidermonkey will optimize this away, but at the moment this is still faster.

**Comment by josdejong** [comment] 2016-02-04 20:16
There is indeed no risk for multi-threading, my concern is the human factor:

```js
        "functionXYZ": function(a, b) {

            parse(a, b); // mutates P

            // some day someone may add some operations here,
            // if these operations mutate P too, we're screwed later on

            return new Complex(
              // uses P, assumes it contains the values set in the initial parse
            )
        },
```

This sort of hidden side effects gives me the creeps. I tend to chose straightforward code over performance in such cases, but well it's up to you. As long as the library is heavily unit tested there should be no risk for the end users and it can mostly give you a headache debugging such a problem.

**Comment by infusion** [comment] 2016-02-04 20:44
I totally agree with that and it's not the way I would it like to be. At the moment every operation is quite small and atomic so that the problem is neglectable. For the human factor, I added the comments to `parse()`, which is quite good. At the end, it's good to use specialized libraries which try to do the job as good as possible (here in terms of numerical stable and in terms of performance).

**Comment by infusion** [comment] 2016-02-04 20:46
I close this issue for now, I use the same technique in other projects as well and when I see a shift in performance, I'll change it in all projects.

**Closed by infusion** 2016-02-04 20:46 UTC
